<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZWQALsz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZWQALsz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZWQALsz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZWQALsz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZWQALsz\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZWQALsz',
    'container.build_id' => '5febb92c',
    'container.build_time' => 1613110295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZWQALsz');
