<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMTgxzeV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMTgxzeV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMTgxzeV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMTgxzeV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMTgxzeV\App_KernelDevDebugContainer([
    'container.build_hash' => 'MTgxzeV',
    'container.build_id' => 'ceb36e25',
    'container.build_time' => 1613154061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMTgxzeV');
